from pathlib import Path

import yt_dlp

from src.utils.file_utils import safe_filename


class YouTubeDownloader:

    def __init__(self):

        self.output_dir = Path("raw/youtube")

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

    def download(self, url):

        output_template = str(
            self.output_dir / "%(title)s.%(ext)s"
        )

        ydl_opts = {
            "format": "bestaudio/best",
            "outtmpl": output_template,
            "quiet": True,
            "noplaylist": True,
            "extractaudio": True,
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "mp3",
                    "preferredquality": "192",
                }
            ],
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:

            info = ydl.extract_info(
                url,
                download=True
            )

            downloaded_file = Path(
                ydl.prepare_filename(info)
            )

        # Final MP3 generated by FFmpeg
        audio_path = downloaded_file.with_suffix(".mp3")

        # Safe title for exporting and metadata
        info["title"] = safe_filename(
            info["title"]
        )

        return {
            "title": info["title"],
            "url": url,
            "audio": str(audio_path),
            "duration": info.get("duration", 0),
            "channel": info.get("uploader", "")
        }