ENABLE_GEMINI_CACHE = True

ENABLE_TRANSCRIPT_CACHE = True

ENABLE_DOWNLOAD_CACHE = True

ENABLE_DUPLICATE_DETECTION = True

ENABLE_LOGGING = True

ENABLE_METADATA = True

ENABLE_QUALITY_CHECK = True

ENABLE_SMART_CHUNKING = True